NAME = 		push_swap

SRC = 		main.c \
			operations/swap_rotate_reverse.c \
			operations/swap_rotate_reverse_b.c \
			operations/list_utils.c \
			operations/push.c \
			operations/double_rotate.c \
			turkishtrick/mechanicalturk.c \
			turkishtrick/mechanicalturk_utils.c \
			turkishtrick/mechanicalturk_utils2.c \
			turkishtrick/mechanicalturk_utils3.c \
			turkishtrick/mechanicalturk_utils4.c \
			turkishtrick/mechanicalturk_utils5.c


OBJ = 		${SRC:.c=.o}

CC = 		gcc

CFLAGS = 	-Wall -Wextra -Werror -fsanitize=address -g

LIB = 		libft/libft.a \
			libftprintf/libftprintf.a

REMOVE = 	rm -f

COMPILE = 	gcc $(CFLAGS) -o $(NAME) -I ./libft -L. $(LIB)


all:		$(NAME)
			@echo "						\033[95mi hate this project"
			@echo ""
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣀⣀⣤⣴⣶⣶⣶⣶⣶⣶⣶⣶⣶⣤⣤⣀⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣶⡾⠿⠛⠋⠉⠉⠁⠀⠀⠀⠀⠀⠀⠀⠉⠉⠉⠛⠿⢷⣶⣤⣀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⣾⠟⠛⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠙⠻⢿⣦⣄⢀⣀⣠⣤⣤⣤⣤⣄⣀⠀⠀⠀⠀⠀"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣤⣾⠟⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠻⣿⣟⠛⠛⠋⠙⠛⠛⠛⠿⣷⣄⠀⠀"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣰⣾⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣀⣀⠀⠀⠀⠀⠀⠀⠀⢠⡶⠶⢦⡀⠀⠀⠈⠻⢷⣄⠀⠀⠀⠀⠀⠀⠈⢻⣷⠀"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣾⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⡏⠀⠈⢳⡄⠀⠀⠀⠀⠀⢸⡇⠀⠀⠻⡄⠀⠀⠀⠀⠻⣧⡀⠀⠀⠀⠀⠀⠀⣿⣇"
			@echo "⠀⠀⠀⠀⠀⠀⠀⠀⠀⣴⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠰⣇⠀⠀⠀⢿⡀⠀⠀⠀⠀⠸⣷⡀⠀⠀⣿⡄⠀⠀⠀⠀⠈⢻⣄⠀⠀⠀⠀⠀⣹⣿"
			@echo "⠀⠀⠀⠀⠀⠀⠀⢀⣼⡿⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⡆⠀⠀⣸⣷⠀⠀⠀⠀⠀⢹⣷⣤⣤⣿⣇⠀⠀⠀⠀⠀⠀⠻⣦⠀⠀⠀⠀⣿⡟"
			@echo "⠀⠀⠀⠀⠀⠀⠀⣼⡟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⣿⣶⣾⣿⣿⡄⠀⠀⠀⠀⠘⣿⣿⣿⣿⣿⡄⠀⠀⠀⠀⠀⠀⢻⣦⠀⠀⣸⣿⠁"
			@echo "⠀⠀⠀⠀⠀⠀⢸⣿⢁⣠⡴⠿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣿⢿⣿⣿⢿⡇⠀⠀⠀⠀⠀⢹⡝⠛⠋⢸⡇⠀⠀⢀⣀⣀⣀⠀⢿⡆⢠⣿⠃⠀"
			@echo "⠀⠀⠀⠀⠀⣠⣿⡿⠟⠉⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢹⡆⠀⠀⢸⡇⠀⠀⠀⠀⠀⠈⢿⡀⠀⢸⡇⢀⣴⣿⣿⣿⣿⡇⠘⣷⣿⠃⠀⠀"
			@echo "⠀⠀⠀⢠⣾⡿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣠⣴⣶⣶⣶⣦⣄⠀⠀⢳⣄⠀⣼⠃⠀⠀⠀⠀⠀⠀⠈⠛⠒⠚⠀⠘⠿⣿⠿⠟⠋⠀⠀⢻⣇⠀⠀⠀"
			@echo "⠀⠀⣰⣿⠋⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢿⣿⣿⣿⣿⣿⣿⡇⠀⠀⠉⠋⠁⠀⠰⣦⣀⣀⣠⣾⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀"
			@echo "⠀⣸⡿⠃⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠉⠉⠙⠋⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠈⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⠀⠀"
			@echo "⢀⣿⠇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⡇⠀⠀"
			@echo "⢸⣿⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⣶⡿⠿⠟⠛⠛⠻⠿⣶⣤⣄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢸⣿⠀⠀⠀"
			@echo "⢸⣿⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣀⣴⠾⠛⠉⣵⣾⣿⠿⠟⠀⠀⠀⠀⠀⠈⠙⢷⡄⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣼⡟⠀⠀⠀"
			@echo "⠀⢿⣧⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣴⠟⠉⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠘⣷⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢰⣿⡇⠀⠀⠀"
			@echo "⠀⠈⠻⣷⣤⡀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⢀⣠⣤⠄⢀⣴⠟⠁⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣿⡇⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⠀⣾⡟⠀⠀⠀⠀\033[0m"

$(NAME): 	$(OBJ)
			make -C libft
			make -C libftprintf
			@$(COMPILE) $(OBJ) -L. $(LIB)

%.o: 		%.c
			$(CC) -c $(CFLAGS) -I./libft -I./libftprintf -o $@ $<

clean:
			$(REMOVE) $(OBJ)
			make -C ./libft clean
			make -C ./libftprintf clean

fclean: 	clean
			$(REMOVE) $(NAME)
			make -C ./libft fclean
			make -C ./libftprintf fclean

re: 		fclean all

.PHONY: all clean fclean re
